MediaJel/mediajel-tracker

src/v2/imports/carts/dutchie-iframe.ts, src/v2/imports/carts/dutchie-subdomain.ts, src/v2/imports/carts/greenrush.ts, src/v2/imports/carts/lightspeed.ts, src/v2/imports/carts/meadow.ts, src/v2/imports/carts/olla.ts, src/v2/imports/carts/shopify.ts, src/v2/imports/carts/tymber.ts, src/v2/imports/carts/woocommerce.ts
Refactor the code within the `src/v2/imports/carts/*` for the use of sp.js including:
- `dutchie-iframe`
- `dutchie-subdomain`
- `greenrush`
- `lightspeed`
- `meadow`
- `olla`
- `shopify`
- `tymber`
- `woocommerce`
=> Refactor Universal Tag Carts to use updated sp.js

src/v1/imports/carts/greenrush.ts, src/v2/imports/carts/greenrush.ts
Description:
Fix greenrush issue on not getting transaction data for v1 and v2.
=> [FOR RE-REVIEW] fix greenrush issues

src/shared/utils/get-context.ts, src/v1/imports/impressions/liquidm.ts, src/v2/imports/impressions/liquidm.ts
=> Update Staging from Develop

src/v1/imports/carts/shopify.ts, src/v1/imports/carts/woocommerce.ts, src/v2/imports/carts/shopify.ts, src/v2/imports/carts/woocommerce.ts
Set up email tracker for carts:
- `woocommerce` v1 and v2
- `shopify` v1 and v2
=> added email tracker for woocommerce and shopify

src/v1/imports/carts/grassdoor.ts, src/v1/imports/carts/index.ts, src/v2/imports/carts/grassdoor.ts, src/v2/imports/carts/index.ts
Added the `grassdoor` v1 and v2 to the cart of universal tag. It's using the `window.dataLayer`.
=> add grassdoor v1 and v2 to the cart

src/shared/interface.ts, src/v1/imports/carts/ecwid.ts, src/v1/imports/carts/index.ts, src/v2/imports/carts/ecwid.ts, src/v2/imports/carts/index.ts
Added `ecwid` w1 and v2 to the cart. For implementing this cart, follow the steps in this link:
[Adding a custom tracking code to your Ecwid store](https://support.ecwid.com/hc/en-us/articles/360009524819-Custom-tracking-code-on-the-Order-Confirmation-page#adding-a-custom-tracking-code-to-your-ecwid-store)
This is the custom script that will be added to the **Custom tracking code on Order Confirmation page** section:
```
<script src='https://tags.cnna.io/?appId=NurseWellness&environment=ecwid'> </script>
<script>
<#noescape>
var transactionOrder = ${order};
var transactionItems = ${order.items};
var email = ${customer.email}
</#noescape>
</script>
```
For the variable references:
[Notification Variables](https://support.ecwid.com/hc/en-us/articles/360009415719)
=> add ecwid v1 and v2 to the cart

src/v1/imports/carts/ecwid.ts, src/v1/imports/carts/index.ts, src/v2/imports/carts/ecwid.ts, src/v2/imports/carts/index.ts
**Addressed the comments of the previous PR:**
=> updates for ecwid

public/index.html, src/plugins/google/imports/carts/jane.ts, src/plugins/google/index.ts, src/shared/interface.ts
using the passed `context.gtag` seems to not work correctly, I have tested using the `window.gtag` function and conversions get tracked properly.
=> use window.gtag vs context.gtag

src/shared/types.ts, src/v1/imports/impression/liquidm.ts, src/v2/imports/impression/liquidm.ts
Remove unrequired click macros due to additional set up in the Liquid M UI for Ops.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203018183096475
=> [FOR REVIEW] Remove unrequired macros

README.md, docs/index.html, src/plugins/bing/imports/carts/tymber.ts, src/plugins/bing/index.ts, src/plugins/google/imports/carts/tymber.ts, src/plugins/google/index.ts, src/shared/environment-data-sources/tymber.ts
Create `Tymber` adapter for Google Ads & Bing Ads #162
=> Create tymber adapter for google ads & bing ads

README.md, public/index.html, src/plugins/index.ts
=> Modify plugin parameter of the universal tag to accept a comma separated list and ensure functionality is preserved

src/shared/environment-data-sources/bigcommerce.ts, src/v1/imports/carts/bigcommerce.ts, src/v1/imports/carts/index.ts, src/v2/imports/carts/bigcommerce.ts
For the Issue:
https://github.com/MediaJel/mediajel-tracker/issues/254
Make a cart for BigCommerce
=> bigcommerce cart

src/shared/environment-data-sources/bigcommerce.ts, src/v1/imports/carts/bigcommerce.ts
https://github.com/MediaJel/mediajel-tracker/issues/268
=> improvements bigcommerce

cypress/e2e/spec.cy.ts, examples/index.html, src/v1/snowplow/events/create-tracker.ts
- Due to adblocker block our domain `cnna.io` We are force to change our domain to `cmpgntrckr.com`
=> [PASSED QA] New Tracker URL due to add blocker issue

public/index.html, src/index.ts, src/shared/utils/get-context.ts, src/v1/snowplow/events/create-tracker.ts, test.html
https://github.com/MediaJel/mediajel-tracker/issues/286
=> multi tags in one page

public/index.html, src/index.ts, src/shared/utils/get-context.ts, src/v1/snowplow/events/create-tracker.ts
=> [QA PASSED] [HOTFIX] Fix multiple tags

public/index.html, src/index.ts, src/shared/utils/get-context.ts, src/v1/snowplow/events/create-tracker.ts
Reverts MediaJel/mediajel-tracker#329
=> Revert "[QA PASSED] [HOTFIX] Fix multiple tags"

public/index.html, src/index.ts, src/shared/utils/get-context.ts, src/v1/snowplow/events/create-tracker.ts, src/v2/imports/carts/bigcommerce.ts
Reverts MediaJel/mediajel-tracker#330
=> Revert "Update main"

src/shared/environment-data-sources/shopify.ts
Reverts MediaJel/mediajel-tracker#355
=> Revert "try shopify new implementation"

public/index.html, src/index.ts
Added logger for datalayerSource for checking.
=> added logger

public/index.html, src/index.ts
Reverts MediaJel/mediajel-tracker#361
=> Revert "added logger"

public/index.html, src/index.ts
Reverts MediaJel/mediajel-tracker#363
=> Revert "test"

public/index.html, src/index.ts
Will be adding this to test on client sites.
=> Added all sources for testing

src/shared/environment-data-sources/tymber.ts
https://coda.io/d/_dsKW6gcriTa?encodedLocationContext=eyJjb21tZW50VGhyZWFkSWQiOiJyLV8yYjBhMUN2aXIiLCJwYWdlSWQiOiJzZWN0aW9uLTc4eWR3cGl4MjgiLCJ0eXBlIjoiZ3JpZCIsIm9iamVjdElkIjoiZ3JpZC1kbUdqMS11U3NUIiwicm93SWQiOiJpLXBMZ3hkRHBCbGYiLCJ2aWV3TW9kZSI6Im1vZGFsIn0
=> fix tymber unit price

public/index.html, src/shared/environment-data-sources/bigcommerce.ts, src/shared/utils/get-context.ts, src/v1/imports/carts/woocommerce.ts, src/v2/imports/carts/bigcommerce.ts, src/v2/imports/carts/buddi.ts, src/v2/imports/carts/dispense.ts, src/v2/imports/carts/dutchie-iframe.ts, src/v2/imports/carts/dutchie-plus.ts, src/v2/imports/carts/dutchie-subdomain.ts, src/v2/imports/carts/ecwid.ts, src/v2/imports/carts/grassdoor.ts, src/v2/imports/carts/greenrush.ts, src/v2/imports/carts/index.ts, src/v2/imports/carts/jane.ts, src/v2/imports/carts/lightspeed.ts, src/v2/imports/carts/meadow.ts, src/v2/imports/carts/olla.ts, src/v2/imports/carts/square.ts, src/v2/imports/carts/sticky-leaf.ts, src/v2/imports/carts/tymber.ts, src/v2/imports/carts/wefunder.ts, src/v2/imports/carts/woocommerce.ts, src/v2/imports/carts/yotpo.ts, src/v2/imports/impression/index.ts, src/v2/imports/impression/mantis.ts
https://github.com/MediaJel/mediajel-tracker/issues/381
=> Migration of carts from v1 to v2

src/shared/environment-data-sources/bigcommerce.ts, src/shared/environment-data-sources/buddi.ts, src/shared/environment-data-sources/dispense.ts, src/shared/environment-data-sources/dutchie-iframe.ts, src/shared/environment-data-sources/dutchie-plus.ts, src/shared/environment-data-sources/dutchie-subdomain.ts, src/shared/environment-data-sources/ecwid.ts, src/shared/environment-data-sources/grassdoor.ts, src/shared/environment-data-sources/greenrush.ts, src/shared/environment-data-sources/jane.ts, src/shared/environment-data-sources/lightspeed.ts, src/shared/environment-data-sources/magento.ts, src/shared/environment-data-sources/meadow.ts, src/shared/environment-data-sources/olla.ts, src/shared/environment-data-sources/shopify.ts, src/shared/environment-data-sources/square.ts, src/shared/environment-data-sources/sticky-leaf.ts, src/shared/environment-data-sources/tymber.ts, src/shared/environment-data-sources/webjoint.ts, src/shared/environment-data-sources/wefunder.ts, src/shared/environment-data-sources/woocommerce.ts, src/shared/environment-data-sources/yotpo.ts
https://github.com/MediaJel/mediajel-tracker/issues/379
=> track errors v1

src/shared/environment-data-sources/bigcommerce.ts, src/shared/environment-data-sources/buddi.ts, src/shared/environment-data-sources/dispense.ts, src/shared/environment-data-sources/dutchie-iframe.ts, src/shared/environment-data-sources/dutchie-plus.ts, src/shared/environment-data-sources/dutchie-subdomain.ts, src/shared/environment-data-sources/ecwid.ts, src/shared/environment-data-sources/grassdoor.ts, src/shared/environment-data-sources/greenrush.ts, src/shared/environment-data-sources/jane.ts, src/shared/environment-data-sources/lightspeed.ts, src/shared/environment-data-sources/magento.ts, src/shared/environment-data-sources/meadow.ts, src/shared/environment-data-sources/olla.ts, src/shared/environment-data-sources/shopify.ts, src/shared/environment-data-sources/square.ts, src/shared/environment-data-sources/sticky-leaf.ts, src/shared/environment-data-sources/tymber.ts, src/shared/environment-data-sources/webjoint.ts, src/shared/environment-data-sources/wefunder.ts, src/shared/environment-data-sources/woocommerce.ts, src/shared/environment-data-sources/yotpo.ts
Reverts MediaJel/mediajel-tracker#408
=> Revert "Staging to Master - v1 track errors"

src/shared/environment-data-sources/bigcommerce.ts, src/shared/environment-data-sources/buddi.ts, src/shared/environment-data-sources/dispense.ts, src/shared/environment-data-sources/dutchie-iframe.ts, src/shared/environment-data-sources/dutchie-plus.ts, src/shared/environment-data-sources/dutchie-subdomain.ts, src/shared/environment-data-sources/ecwid.ts, src/shared/environment-data-sources/grassdoor.ts, src/shared/environment-data-sources/greenrush.ts, src/shared/environment-data-sources/jane.ts, src/shared/environment-data-sources/lightspeed.ts, src/shared/environment-data-sources/magento.ts, src/shared/environment-data-sources/meadow.ts, src/shared/environment-data-sources/olla.ts, src/shared/environment-data-sources/shopify.ts, src/shared/environment-data-sources/square.ts, src/shared/environment-data-sources/sticky-leaf.ts, src/shared/environment-data-sources/tymber.ts, src/shared/environment-data-sources/webjoint.ts, src/shared/environment-data-sources/wefunder.ts, src/shared/environment-data-sources/woocommerce.ts, src/shared/environment-data-sources/yotpo.ts
Reverts MediaJel/mediajel-tracker#406
=> Revert "track errors v1" STAGING

src/shared/environment-data-sources/ecwid.ts, src/shared/sources/poll-for-element.ts, src/v1/imports/carts/ecwid.ts, src/v2/imports/carts/ecwid.ts
A ticket came which doesn't use the current way of getting data from Ecwid cart. 
* Added changes to Ecwid cart on environment-data-sources.
* Added poll-for-element on sources.
=> Updated Ecwid Cart

src/shared/types.ts
Define advertiserName on ImpressionsMacrosParams
=> Define advertiserName on ImpressionsMacrosParams

.circleci/config.yml, package-lock.json, package.json, public/index.html, src/scripts/environment.js, src/scripts/generateEnvironments.ts, yarn.lock
https://github.com/MediaJel/mediajel-tracker/issues/420
- CI WORKFLOW is still TODO
Needed ENV
```
ASK DEVOPS or JON for ENV Variables
```
=> feature:generate environments on index file and upload to s3

src/scripts/environment.js, src/scripts/generateEnvironments.ts, src/v1/imports/carts/index.ts
Ticket: https://github.com/MediaJel/amplication-nestjs-microservices/issues/299
https://mjcarts.s3.amazonaws.com/environments.js
=> generate carts added with events tracked and description

src/scripts/environment.js, src/scripts/generateEnvironments.ts
just a follow up clean code for 
https://github.com/MediaJel/mediajel-tracker/pull/448
=> updates needed for environment events

src/shared/environment-data-sources/wix.ts, src/v1/imports/carts/thirdparty.ts, src/v1/imports/carts/wix.ts, src/v2/imports/carts/dutchie-plus.ts, src/v2/imports/carts/wix.ts
https://github.com/MediaJel/mediajel-tracker/issues/473
and 
https://github.com/MediaJel/amplication-nestjs-microservices/issues/367#issuecomment-2261365604
=> wix adapter and v2 carts fixes

src/shared/environment-data-sources/sweed.ts, src/v1/imports/carts/index.ts, src/v1/imports/carts/sweed.ts, src/v2/imports/carts/index.ts, src/v2/imports/carts/sweed.ts
All new Sweed Cart
Tested the same code for both with the same cart named sweed
https://shop.californiaholistics.com/
https://shop.oxnardholistics.com/
=> add sweed cart

src/v1/imports/carts/index.ts
Sweed is currently have a bug issue duplication for add and remove to cart when running display ads and google ads at the same time
=> update kpi events

src/shared/environment-data-sources/sweed.ts
Adding add and remove cart since the datalayer source issue with the plugin has been fixed
=> sweed cart add and remove cart

src/adapters/ecommerce.ts, src/shared/environment-data-sources/foxy.ts
https://github.com/MediaJel/mediajel-tracker/issues/561 - Ticket Issue
=> add foxy environment

src/adapters/impressions.ts, src/shared/snowplow/types.ts, src/shared/snowplow/v1/impressions.ts, src/shared/snowplow/v2/impressions.ts, src/shared/sources/error-tracking-source.ts
- **fix: changed value of message in errorTracking**
- **feat: created simplifi adapter for impression**
=> Simplifi Adapter

src/shared/environment-data-sources/tymber.ts
For Issue: https://github.com/MediaJel/mediajel-tracker/issues/570
=> try fix tymber cart issue

.circleci/config.yml, .parcelrc, package.json, public/index.html, src/shared/segment-builder/segments/dstillery.ts, src/shared/segment-builder/segments/nexxen.ts, src/shared/utils/create-image-pixel.ts, yarn.lock
- **fix: changed value of message in errorTracking**
- **feat: created simplifi adapter for impression**
- **fix: revert value of message in errorTracking**
- **fix: change value of lineItemId to simplify**
- **feat: Add createImagePixel utility function**
- **fix: append img pixel outside function**
=> Fix on Image Pixels for Segments

src/adapters/ecommerce.ts, src/shared/environment-data-sources/blaze.ts
For site QA:
```javascript
const xhrResponseSource = callback => {
const origOpen = XMLHttpRequest.prototype.open
XMLHttpRequest.prototype.open = function() {
this.addEventListener("load", () => callback(this))
origOpen.apply(this, arguments)
}
}
xhrResponseSource((xhr) => {
try {
const getData = JSON.parse(xhr.responseText);
console.log('xhr response getData ',getData);
if (getData.data.type === "orders") {
console.log("Inside Order");
const transaction = getData.data.attributes;
const amount = (transaction.total.amount/100).toString();
const tax = (transaction.tax_total.amount/100).toString();
const products = getData.included;
const address = transaction.delivery_address;
window.tracker("addTrans", {
orderId: transaction.order_number.toString(),
affiliation: "N/A",
total: …
```
=> Added blaze adapter

CODEOWNERS, src/shared/environment-data-sources/blaze.ts
Fix Blaze cart and also added codeowners
=> Fix blaze cart and added codeowners

src/adapters/ecommerce.ts, src/scripts/environment.js, src/shared/environment-data-sources/drupal.ts
Tested with the same code but from the frictionless tag 
Also to take note is that edobles in the frictionless is using this same code so remove the frictionless implementation once this is up
=> Added drupal adapter

src/adapters/ecommerce.ts, src/scripts/environment.js, src/shared/environment-data-sources/ticketmaster.ts
https://github.com/MediaJel/mediajel-tracker/issues/642
=> ticketmaster adapter

public/index.html, src/adapters/index.ts, src/shared/interface.ts, src/shared/snowplow/extensions/register-third-party-tags.ts, src/shared/types.ts
https://github.com/MediaJel/mediajel-tracker/issues/591
=> thirdparty tags

src/adapters/ecommerce.ts, src/shared/environment-data-sources/ticketure.ts
This pull request includes changes to add support for a new data source, "ticketure", in the ecommerce adapter. The most important changes include the addition of a new case for "ticketure" in the ecommerce adapter and the creation of a new data source module for "ticketure" that reuses the "ticketmaster" data source.
* [`src/adapters/ecommerce.ts`](diffhunk://#diff-fd24e953cfd3e4c04096be9762739fbdc8cb7f37ca36b9b0145ce868769ebd2cR133-R137): Added a new case for "ticketure" to import and load the "ticketure" data source module.
* [`src/shared/environment-data-sources/ticketure.ts`](diffhunk://#diff-6490ddda95fea07cd6fda084f8cbc49c898d8d738f1a7731cecac90b77bc7b86R1-R7): Created a new module for the "ticketure" data source that imports and utilizes the existing "ticketmaster" data source.
=> added ticketure

src/adapters/ecommerce.ts, src/shared/environment-data-sources/tnew.ts
This pull request includes changes to the `src/adapters/ecommerce.ts` and `src/shared/environment-data-sources/tnew.ts` files to add support for a new data source, `tnew`.
* [`src/adapters/ecommerce.ts`](diffhunk://#diff-fd24e953cfd3e4c04096be9762739fbdc8cb7f37ca36b9b0145ce868769ebd2cR138-R142): Added a new case for "tnew" which imports and loads the `tnew` data source.
* [`src/shared/environment-data-sources/tnew.ts`](diffhunk://#diff-8568728dce34dfa32156c2d43e367f68b5fa9317d9667c50241164fd3d718648R1-R7): Created a new file that imports the `foxy` data source and defines a function `tnewDataSource` that calls `foxyDataSource`. This function is exported as the default export.
=> added tnew adapter for indianapolissymphony

public/index.html, src/index.ts, src/shared/logger.ts, src/shared/sources/xhr-request-source.ts, src/shared/types.ts, src/shared/utils/datasource-logger.ts
Add extra param on tag `findSource=true` to log datasource.
=> Add Datasource Logger when debug=true on tag

src/shared/snowplow/extensions/deduplicator.ts
=> Allow Deduplicator to accept array of IDs

cypress/e2e/woocommerce.spec.cy.ts
to test 
yarn cy:open
Ticket Issue:
https://github.com/MediaJel/mediajel-tracker/issues/713
=> add woocommerce test
